### ISSUE TITLE
Shifting DIV position does not shift the map nor touchable region

### ISSUE THREAD

**Issue by silencer22** [mapsplugin/cordova-plugin-googlemaps#976]
Hello, with response to users' interaction, I adjusted the position of the div containing the google map using Javascript. I have tried calling refreshLayout or setPadding, neither of them updates the touchable region of the map, so now a part of the map is hidden behind another div.

Is there any way to update the map region? Thanks!

Javascript
```javascript
document.getElementById("mapCanvas").setAttribute('style','top:76px;');
gmap.setPadding( 20, 0 , 0 , 0 );
gmap.refreshLayout();
```

Original CSS styling in the stylesheet
```css
.gmap {
    width:100%;
    height:100%;
    position: fixed;
    left:0px;
    top:56px;
    z-index: 2;
}
```

HTML markup
```html
<div class="navBar" id="navBar"></div>
<div class="gmap gmapBg" id="mapCanvas"></div>
```
